name: HunterVsSpeedrunner
version: 0.2
author: Leglord
main: me.Leglord.HunterVsSpeedrunner.Main
description: 1.16.1 Hunter vs Speedrunner challenge plugin.

commands:
  compass:
    aliases: [hunt, track]
    description:  gives speedrunner-tracking compass to hunter
  untrack:
    aliases: [goodbye]
    description:  stops tracking Speedrunnner